export const SEVEN_KOLS_CONTRACT_ADDRESS = "0x9C2e9b5b9dDa8268912403e7DDE7ABAe14985cb0";
export const SEVEN_KOLS_ABI = [
    {
      "inputs":[{"internalType":"address","name":"","type":"address"}],
      "name":"users",
      "outputs":[
        {"internalType":"address","name":"referrer","type":"address"},
        {"internalType":"uint256","name":"totalDeposited","type":"uint256"},
        {"internalType":"uint256","name":"totalEarned","type":"uint256"},
        {"internalType":"uint256","name":"totalWithdrawn","type":"uint256"},
        {"internalType":"uint256","name":"pendingReward","type":"uint256"},
        {"internalType":"uint256","name":"downlineCount","type":"uint256"},
        {"internalType":"bool","name":"registered","type":"bool"}
      ],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[{"internalType":"address","name":"_referrer","type":"address"}],
      "name":"depositAndClaim",
      "outputs":[],
      "stateMutability":"nonpayable",
      "type":"function"
    },
    {
      "inputs":[{"internalType":"address","name":"_user","type":"address"}],
      "name":"getDirectReferrals",
      "outputs":[{"internalType":"address[]","name":"","type":"address[]"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[{"internalType":"address","name":"_user","type":"address"}],
      "name":"getUpline6",
      "outputs":[{"internalType":"address[6]","name":"","type":"address[6]"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[{"internalType":"address","name":"_user","type":"address"}],
      "name":"getPendingReward",
      "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[{"internalType":"address","name":"_user","type":"address"}],
      "name":"getTotalEarning",
      "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"getTotalUsers",
      "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"getTotalDeposited",
      "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"getTotalSentToTreasury",
      "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"getTotalFeeAmount",
      "outputs":[{"internalType":"uint256","name":"","type":"uint256"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"getLastJoinedUser",
      "outputs":[{"internalType":"address","name":"","type":"address"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"usdtToken",
      "outputs":[{"internalType":"address","name":"","type":"address"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"treasuryWallet",
      "outputs":[{"internalType":"address","name":"","type":"address"}],
      "stateMutability":"view",
      "type":"function"
    },
    {
      "inputs":[],
      "name":"feeWallet",
      "outputs":[{"internalType":"address","name":"","type":"address"}],
      "stateMutability":"view",
      "type":"function"
    }
  ];